# Generated by Django 5.2.13 on 2026-04-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DietPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_number', models.PositiveSmallIntegerField(default=1)),
                ('meals', models.JSONField(default=dict)),
                ('recommendations', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('category', models.CharField(choices=[('fruit', 'Fruit'), ('vegetable', 'Vegetable'), ('protein', 'Protein'), ('dairy', 'Dairy'), ('grain', 'Grain'), ('snack', 'Snack'), ('other', 'Other')], default='other', max_length=32)),
                ('organic', models.BooleanField(default=False)),
                ('safety_score', models.PositiveSmallIntegerField(default=85)),
                ('farm_origin', models.CharField(blank=True, help_text='Farm label or future on-chain hash reference', max_length=255)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
