# Generated by Django 5.2.13 on 2026-04-25 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('nutrition', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dietplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diet_plans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='dietplan',
            index=models.Index(fields=['user', '-updated_at'], name='nutrition_d_user_id_ed9d37_idx'),
        ),
    ]
