# Generated by Django 5.2.13 on 2026-04-25 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('market', '0001_initial'),
        ('nutrition', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productavailability',
            name='food_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='nutrition.fooditem'),
        ),
        migrations.AddField(
            model_name='seller',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sellers', to='market.location'),
        ),
        migrations.AddField(
            model_name='productavailability',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='market.seller'),
        ),
        migrations.AlterUniqueTogether(
            name='productavailability',
            unique_together={('seller', 'food_item')},
        ),
    ]
