# Generated by Django 5.2.13 on 2026-04-25 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('slug', models.SlugField(unique=True)),
                ('summary', models.TextField(blank=True)),
                ('body', models.TextField()),
                ('category', models.CharField(choices=[('nutrition', 'Nutrition'), ('health', 'Health'), ('pregnancy', 'Pregnancy tips'), ('weekly', 'Weekly recommendation')], default='nutrition', max_length=32)),
                ('trimester', models.CharField(blank=True, help_text='1/2/3 or blank for all', max_length=1)),
                ('published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
